/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressBookRecipientMetadata {
    /// Nickname related to the address.
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    /// Email of the user.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Blockchain Name Service (e.g. ENS) domain for the address.
    #[serde(rename = "bns", skip_serializing_if = "Option::is_none")]
    pub bns: Option<String>,
}

impl AddressBookRecipientMetadata {
    pub fn new() -> AddressBookRecipientMetadata {
        AddressBookRecipientMetadata {
            nickname: None,
            email: None,
            bns: None,
        }
    }
}

