/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Balances : Available and unsettled balances of the merchant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Balances {
    /// List of currency balances (one for each currency) that are currently available to spend.
    #[serde(rename = "available")]
    pub available: Vec<models::Money>,
    /// List of currency balances (one for each currency) that have been captured but are currently in the process of settling and will become available to spend at some point in the future.
    #[serde(rename = "unsettled")]
    pub unsettled: Vec<models::Money>,
}

impl Balances {
    /// Available and unsettled balances of the merchant.
    pub fn new(available: Vec<models::Money>, unsettled: Vec<models::Money>) -> Balances {
        Balances {
            available,
            unsettled,
        }
    }
}

