/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BankDestination : The destination bank account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankDestination {
    #[serde(rename = "type")]
    pub r#type: models::BusinessAccountPayoutDestinationType,
    /// Unique system generated identifier for the entity.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Bank name plus last four digits of the bank account number or IBAN.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl BankDestination {
    /// The destination bank account.
    pub fn new(r#type: models::BusinessAccountPayoutDestinationType, id: uuid::Uuid) -> BankDestination {
        BankDestination {
            r#type,
            id,
            name: None,
        }
    }
}

