/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BankAddress : The address details for the bank, as provided during bank account creation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankAddress {
    /// Name of the bank. This property is required for bank accounts outside of the US that do not support IBAN'
    #[serde(rename = "bankName", skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    /// City portion of the address. This property is required for bank accounts outside of the US.
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Country portion of the address. Formatted as a two-letter country code specified in ISO 3166-1 alpha-2.
    #[serde(rename = "country")]
    pub country: String,
    /// Line one of the street address.
    #[serde(rename = "line1", skip_serializing_if = "Option::is_none")]
    pub line1: Option<String>,
    /// Line two of the street address.
    #[serde(rename = "line2", skip_serializing_if = "Option::is_none")]
    pub line2: Option<String>,
    /// State / County / Province / Region portion of the address. US and Canada use the two-letter code for the subdivision.
    #[serde(rename = "district", skip_serializing_if = "Option::is_none")]
    pub district: Option<String>,
}

impl BankAddress {
    /// The address details for the bank, as provided during bank account creation.
    pub fn new(country: String) -> BankAddress {
        BankAddress {
            bank_name: None,
            city: None,
            country,
            line1: None,
            line2: None,
            district: None,
        }
    }
}

