/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessAccountPayoutDestinationType : The destination bank account type.
/// The destination bank account type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BusinessAccountPayoutDestinationType {
    #[serde(rename = "wire")]
    Wire,
    #[serde(rename = "cbit")]
    Cbit,

}

impl std::fmt::Display for BusinessAccountPayoutDestinationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Wire => write!(f, "wire"),
            Self::Cbit => write!(f, "cbit"),
        }
    }
}

impl Default for BusinessAccountPayoutDestinationType {
    fn default() -> BusinessAccountPayoutDestinationType {
        Self::Wire
    }
}

