/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardCreationRequest {
    /// Universally unique identifier (UUID v4) idempotency key. This key is utilized to ensure exactly-once execution of mutating requests.
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: uuid::Uuid,
    /// Universally unique identifier (UUID v4) of the public key used in encryption. NOTE the sandbox environment uses the default value of `key1`. For this reason the example supplied is `key1` rather than a UUID.
    #[serde(rename = "keyId", skip_serializing_if = "Option::is_none")]
    pub key_id: Option<uuid::Uuid>,
    /// PGP encrypted base64 encoded string. Contains Number and CVV. * **Number**: Card number. No spaces or other separators. REQUIRED * **CVV (Card Verification Number)**: Three or four digit security code. REQUIRED' 
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "encryptedData")]
    pub encrypted_data: Vec<u8>,
    #[serde(rename = "billingDetails")]
    pub billing_details: models::BillingDetails,
    /// Two digit number representing the card's expiration month.
    #[serde(rename = "expMonth")]
    pub exp_month: i32,
    /// Four digit number representing the card's expiration year.
    #[serde(rename = "expYear")]
    pub exp_year: i32,
    #[serde(rename = "metadata")]
    pub metadata: models::MetadataCardAndAch,
}

impl CardCreationRequest {
    pub fn new(idempotency_key: uuid::Uuid, encrypted_data: Vec<u8>, billing_details: models::BillingDetails, exp_month: i32, exp_year: i32, metadata: models::MetadataCardAndAch) -> CardCreationRequest {
        CardCreationRequest {
            idempotency_key,
            key_id: None,
            encrypted_data,
            billing_details,
            exp_month,
            exp_year,
            metadata,
        }
    }
}

