/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CardVerificationResponse : Indicates the status of the card for verification purposes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardVerificationResponse {
    /// Status of the AVS check. Raw AVS response, expressed as an upper-case letter. `not_requested` indicates check was not made. `pending` is pending/processing.
    #[serde(rename = "avs")]
    pub avs: String,
    #[serde(rename = "cvv")]
    pub cvv: models::CvvResults,
}

impl CardVerificationResponse {
    /// Indicates the status of the card for verification purposes.
    pub fn new(avs: String, cvv: models::CvvResults) -> CardVerificationResponse {
        CardVerificationResponse {
            avs,
            cvv,
        }
    }
}

