/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChargebackCategories : Enumerated category of the chargeback status codes based on the chargeback status code.
/// Enumerated category of the chargeback status codes based on the chargeback status code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChargebackCategories {
    #[serde(rename = "Canceled Recurring Payment")]
    CanceledRecurringPayment,
    #[serde(rename = "Customer Dispute")]
    CustomerDispute,
    #[serde(rename = "Fraudulent")]
    Fraudulent,
    #[serde(rename = "General")]
    General,
    #[serde(rename = "Processing Error")]
    ProcessingError,
    #[serde(rename = "Not Defined")]
    NotDefined,

}

impl std::fmt::Display for ChargebackCategories {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CanceledRecurringPayment => write!(f, "Canceled Recurring Payment"),
            Self::CustomerDispute => write!(f, "Customer Dispute"),
            Self::Fraudulent => write!(f, "Fraudulent"),
            Self::General => write!(f, "General"),
            Self::ProcessingError => write!(f, "Processing Error"),
            Self::NotDefined => write!(f, "Not Defined"),
        }
    }
}

impl Default for ChargebackCategories {
    fn default() -> ChargebackCategories {
        Self::CanceledRecurringPayment
    }
}

