/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutSessionMoney {
    /// Magnitude of the amount, in units of the currency, with a `.`.
    #[serde(rename = "amount")]
    pub amount: String,
    /// A currency associated with a balance or address.
    #[serde(rename = "currency")]
    pub currency: Currency,
}

impl CheckoutSessionMoney {
    pub fn new(amount: String, currency: Currency) -> CheckoutSessionMoney {
        CheckoutSessionMoney {
            amount,
            currency,
        }
    }
}
/// A currency associated with a balance or address.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "USD")]
    Usd,
    #[serde(rename = "ETH")]
    Eth,
    #[serde(rename = "BTC")]
    Btc,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Usd
    }
}

