/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CryptoPaymentNetworkFee {
    /// Magnitude of the amount, in units of the currency, with a `.`.
    #[serde(rename = "amount")]
    pub amount: String,
    /// Currency code for the amount.
    #[serde(rename = "currency")]
    pub currency: Currency,
    /// The party that pays the network fee based on merchant configuration.
    #[serde(rename = "feePayer", skip_serializing_if = "Option::is_none")]
    pub fee_payer: Option<FeePayer>,
}

impl CryptoPaymentNetworkFee {
    pub fn new(amount: String, currency: Currency) -> CryptoPaymentNetworkFee {
        CryptoPaymentNetworkFee {
            amount,
            currency,
            fee_payer: None,
        }
    }
}
/// Currency code for the amount.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "USD")]
    Usd,
    #[serde(rename = "EUR")]
    Eur,
    #[serde(rename = "BTC")]
    Btc,
    #[serde(rename = "ETH")]
    Eth,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Usd
    }
}
/// The party that pays the network fee based on merchant configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeePayer {
    #[serde(rename = "endUser")]
    EndUser,
    #[serde(rename = "merchant")]
    Merchant,
}

impl Default for FeePayer {
    fn default() -> FeePayer {
        Self::EndUser
    }
}

