/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CryptoRefundCreationRequestAmount : The source amount of the refund, it can be in either the original payment currency or the settlement currency.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CryptoRefundCreationRequestAmount {
    /// Currency code.
    #[serde(rename = "currency")]
    pub currency: Currency,
}

impl CryptoRefundCreationRequestAmount {
    /// The source amount of the refund, it can be in either the original payment currency or the settlement currency.
    pub fn new(currency: Currency) -> CryptoRefundCreationRequestAmount {
        CryptoRefundCreationRequestAmount {
            currency,
        }
    }
}
/// Currency code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "USD")]
    Usd,
    #[serde(rename = "ETH")]
    Eth,
    #[serde(rename = "BTC")]
    Btc,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Usd
    }
}

