/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CryptoPayoutDestination : The destination.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CryptoPayoutDestination {
    #[serde(rename = "type")]
    pub r#type: models::CryptoPayoutDestinationType,
    /// Unique system generated identifier for the entity.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl CryptoPayoutDestination {
    /// The destination.
    pub fn new(r#type: models::CryptoPayoutDestinationType, id: uuid::Uuid) -> CryptoPayoutDestination {
        CryptoPayoutDestination {
            r#type,
            id,
        }
    }
}

