/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeRateRequest {
    /// Amount (Optional) and currency to convert from. If an amount is provided here, then the amount in the \"to\" field must be null.
    #[serde(rename = "from")]
    pub from: Box<models::FiatOptionalAmountMoney>,
    /// Amount (Optional) and currency to convert to. If an amount is provided here, then the amount in the \"from\" field must be null.
    #[serde(rename = "to")]
    pub to: Box<models::FiatOptionalAmountMoney>,
}

impl ExchangeRateRequest {
    pub fn new(from: models::FiatOptionalAmountMoney, to: models::FiatOptionalAmountMoney) -> ExchangeRateRequest {
        ExchangeRateRequest {
            from: Box::new(from),
            to: Box::new(to),
        }
    }
}

