/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtendCheckoutSessionRequest {
    /// Extend the CheckoutSession by extendTime seconds if it is active or expired. The field is optional, if not provided, extend a period that configured by Merchant (default 1 day)
    #[serde(rename = "extendTime", skip_serializing_if = "Option::is_none")]
    pub extend_time: Option<i32>,
}

impl ExtendCheckoutSessionRequest {
    pub fn new() -> ExtendCheckoutSessionRequest {
        ExtendCheckoutSessionRequest {
            extend_time: None,
        }
    }
}

