/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fee {
    /// Magnitude of the fee amount, in units of the currency, with a `.`.
    #[serde(rename = "amount")]
    pub amount: String,
    /// Currency code for the amount.
    #[serde(rename = "currency")]
    pub currency: Currency,
    /// Category of the fee.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Fee {
    pub fn new(amount: String, currency: Currency, r#type: Type) -> Fee {
        Fee {
            amount,
            currency,
            r#type,
        }
    }
}
/// Currency code for the amount.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "USD")]
    Usd,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Usd
    }
}
/// Category of the fee.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "network")]
    Network,
}

impl Default for Type {
    fn default() -> Type {
        Self::Network
    }
}

