/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FiatOptionalAmountMoney {
    /// Magnitude of the amount, in units of the currency, with a `.`.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "currency")]
    pub currency: models::FiatCurrency,
}

impl FiatOptionalAmountMoney {
    pub fn new(currency: models::FiatCurrency) -> FiatOptionalAmountMoney {
        FiatOptionalAmountMoney {
            amount: None,
            currency,
        }
    }
}

