/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MockChargebackCreationRequest {
    /// The id of the payment to be charged back.  Each payment can only be charged back once.
    #[serde(rename = "paymentId")]
    pub payment_id: uuid::Uuid,
}

impl MockChargebackCreationRequest {
    pub fn new(payment_id: uuid::Uuid) -> MockChargebackCreationRequest {
        MockChargebackCreationRequest {
            payment_id,
        }
    }
}

