/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentTokenRequestTokenData : The token data
/// The token data
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PaymentTokenRequestTokenData {
    ApplePayToken(models::ApplePayToken),
    GooglePayToken(models::GooglePayToken),
}

impl Default for PaymentTokenRequestTokenData {
    fn default() -> Self {
        Self::ApplePayToken(Default::default())
    }
}
/// ApplePay token version information.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "EC_v1")]
    EcV1,
    #[serde(rename = "RSA_v1")]
    RsaV1,
}

impl Default for Version {
    fn default() -> Version {
        Self::EcV1
    }
}

