/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentIntentFees {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Magnitude of the amount, in units of the currency, with a `.`.
    #[serde(rename = "amount")]
    pub amount: String,
    /// Currency code.
    #[serde(rename = "currency")]
    pub currency: Currency,
}

impl PaymentIntentFees {
    pub fn new(r#type: Type, amount: String, currency: Currency) -> PaymentIntentFees {
        PaymentIntentFees {
            r#type,
            amount,
            currency,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "blockchainLeaseFee")]
    BlockchainLeaseFee,
    #[serde(rename = "totalPaymentFees")]
    TotalPaymentFees,
}

impl Default for Type {
    fn default() -> Type {
        Self::BlockchainLeaseFee
    }
}
/// Currency code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "USD")]
    Usd,
    #[serde(rename = "BTC")]
    Btc,
    #[serde(rename = "ETH")]
    Eth,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Usd
    }
}

