/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PayoutDestinationType : The destination type.
/// The destination type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayoutDestinationType {
    #[serde(rename = "address_book")]
    AddressBook,

}

impl std::fmt::Display for PayoutDestinationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AddressBook => write!(f, "address_book"),
        }
    }
}

impl Default for PayoutDestinationType {
    fn default() -> PayoutDestinationType {
        Self::AddressBook
    }
}

