/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PresignResponse : Response of the GET /presign endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresignResponse {
    #[serde(rename = "typedData")]
    pub typed_data: models::PresignResponseTypedData,
}

impl PresignResponse {
    /// Response of the GET /presign endpoint
    pub fn new(typed_data: models::PresignResponseTypedData) -> PresignResponse {
        PresignResponse {
            typed_data,
        }
    }
}

