/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresignDomain {
    /// User readable name of signing domain
    #[serde(rename = "name")]
    pub name: String,
    /// The address of the contract that will verify the signature
    #[serde(rename = "verifyingContract")]
    pub verifying_contract: String,
    /// The current major version of the signing domain. Signatures from different versions are not compatible
    #[serde(rename = "version")]
    pub version: String,
    /// chain id from https://chainid.network/
    #[serde(rename = "chainId")]
    pub chain_id: i32,
}

impl PresignDomain {
    pub fn new(name: String, verifying_contract: String, version: String, chain_id: i32) -> PresignDomain {
        PresignDomain {
            name,
            verifying_contract,
            version,
            chain_id,
        }
    }
}

