/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rate {
    /// The buy rate denominated in the quote currency of the trading pair.
    #[serde(rename = "buy")]
    pub buy: String,
    /// The sell rate denominated in the quote currency of the trading pair.
    #[serde(rename = "sell")]
    pub sell: String,
    /// ISO-8601 UTC date/time format.
    #[serde(rename = "createDate")]
    pub create_date: String,
}

impl Rate {
    pub fn new(buy: String, sell: String, create_date: String) -> Rate {
        Rate {
            buy,
            sell,
            create_date,
        }
    }
}

