/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Settlement {
    /// Unique system generated identifier for the entity.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Unique system generated identifier for the wallet of the merchant.
    #[serde(rename = "merchantWalletId", skip_serializing_if = "Option::is_none")]
    pub merchant_wallet_id: Option<String>,
    /// If this settlement was used for a marketplace payment, the wallet involved in the settlement. Not included for standard merchant settlements.
    #[serde(rename = "walletId", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    #[serde(rename = "totalDebits", skip_serializing_if = "Option::is_none")]
    pub total_debits: Option<models::FiatMoneyUsd>,
    #[serde(rename = "totalCredits", skip_serializing_if = "Option::is_none")]
    pub total_credits: Option<models::FiatMoneyUsd>,
    #[serde(rename = "paymentFees", skip_serializing_if = "Option::is_none")]
    pub payment_fees: Option<models::FiatMoneyUsd>,
    #[serde(rename = "chargebackFees", skip_serializing_if = "Option::is_none")]
    pub chargeback_fees: Option<models::FiatMoneyUsd>,
    /// ISO-8601 UTC date/time format.
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// ISO-8601 UTC date/time format.
    #[serde(rename = "updateDate", skip_serializing_if = "Option::is_none")]
    pub update_date: Option<String>,
}

impl Settlement {
    pub fn new() -> Settlement {
        Settlement {
            id: None,
            merchant_wallet_id: None,
            wallet_id: None,
            total_debits: None,
            total_credits: None,
            payment_fees: None,
            chargeback_fees: None,
            create_date: None,
            update_date: None,
        }
    }
}

