/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimpleBillingDetails : Billing details of the card holder.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleBillingDetails {
    /// Country portion of the address. Formatted as a two-letter country code specified in ISO 3166-1 alpha-2.
    #[serde(rename = "country")]
    pub country: String,
    /// State / County / Province / Region portion of the address. US and Canada use the two-letter code for the subdivision.
    #[serde(rename = "district")]
    pub district: String,
}

impl SimpleBillingDetails {
    /// Billing details of the card holder.
    pub fn new(country: String, district: String) -> SimpleBillingDetails {
        SimpleBillingDetails {
            country,
            district,
        }
    }
}

