/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionRequest {
    /// URL of the subscriber endpoint. Must be publicly accessible and utilize HTTPS.
    #[serde(rename = "endpoint")]
    pub endpoint: String,
}

impl SubscriptionRequest {
    pub fn new(endpoint: String) -> SubscriptionRequest {
        SubscriptionRequest {
            endpoint,
        }
    }
}

