/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferCreationRequest {
    /// Universally unique identifier (UUID v4) idempotency key. This key is utilized to ensure exactly-once execution of mutating requests.
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: uuid::Uuid,
    #[serde(rename = "source")]
    pub source: models::TransferRequestSourceWalletLocation,
    #[serde(rename = "destination")]
    pub destination: models::TransferCreationRequestDestination,
    #[serde(rename = "amount")]
    pub amount: models::Money,
}

impl TransferCreationRequest {
    pub fn new(idempotency_key: uuid::Uuid, source: models::TransferRequestSourceWalletLocation, destination: models::TransferCreationRequestDestination, amount: models::Money) -> TransferCreationRequest {
        TransferCreationRequest {
            idempotency_key,
            source,
            destination,
            amount,
        }
    }
}

