/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransferCreationRequestDestination {
    TransferRequestBlockchainLocation(models::TransferRequestBlockchainLocation),
    WalletLocation(models::WalletLocation),
}

impl Default for TransferCreationRequestDestination {
    fn default() -> Self {
        Self::TransferRequestBlockchainLocation(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "blockchain")]
    Blockchain,
    #[serde(rename = "wallet")]
    Wallet,
}

impl Default for Type {
    fn default() -> Type {
        Self::Blockchain
    }
}

