/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferSourceLocation : A source of funds.
/// A source of funds.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransferSourceLocation {
    TransferSourceWalletLocation(models::TransferSourceWalletLocation),
    TransferSourceBlockchainLocation(models::TransferSourceBlockchainLocation),
}

impl Default for TransferSourceLocation {
    fn default() -> Self {
        Self::TransferSourceWalletLocation(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "wallet")]
    Wallet,
    #[serde(rename = "blockchain")]
    Blockchain,
}

impl Default for Type {
    fn default() -> Type {
        Self::Wallet
    }
}

