/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferDestinationLocation : A destination of funds.
/// A destination of funds.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransferDestinationLocation {
    TransferDestinationBlockchainLocation(Box<models::TransferDestinationBlockchainLocation>),
    TransferDestinationWalletLocation(Box<models::TransferDestinationWalletLocation>),
}

impl Default for TransferDestinationLocation {
    fn default() -> Self {
        Self::TransferDestinationBlockchainLocation(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "blockchain")]
    Blockchain,
    #[serde(rename = "wallet")]
    Wallet,
}

impl Default for Type {
    fn default() -> Type {
        Self::Blockchain
    }
}

