/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WireInstructionBeneficiaryBank {
    /// Name of the beneficiary's bank.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// SWIFT code of the beneficiary's bank account.
    #[serde(rename = "swiftCode", skip_serializing_if = "Option::is_none")]
    pub swift_code: Option<String>,
    /// ABA Routing number of the beneficiary's bank account.
    #[serde(rename = "routingNumber", skip_serializing_if = "Option::is_none")]
    pub routing_number: Option<String>,
    /// Account number of the beneficiary's bank account.
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    /// Currency of the beneficiary's bank account.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Address of the beneficiary's bank.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// City of the beneficiary's bank.
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Postal code of the beneficiary's bank.
    #[serde(rename = "postalCode", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    /// Country code of the beneficiary's bank. Formatted as a two-letter country code specified in ISO 3166-1 alpha-2.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

impl WireInstructionBeneficiaryBank {
    pub fn new() -> WireInstructionBeneficiaryBank {
        WireInstructionBeneficiaryBank {
            name: None,
            swift_code: None,
            routing_number: None,
            account_number: None,
            currency: None,
            address: None,
            city: None,
            postal_code: None,
            country: None,
        }
    }
}

