/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Wire {
    /// Unique system generated identifier for the entity.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::ExternalFiatAccountStatus,
    /// Bank name plus last four digits of the bank account number or IBAN.
    #[serde(rename = "description")]
    pub description: String,
    /// Wire tracking ref that needs to be set in the wire reference to beneficiary field.
    #[serde(rename = "trackingRef")]
    pub tracking_ref: String,
    /// A <TransferType, TransferTypeInfo> map which shows transfer types supported on this account as well as additional information for each.
    #[serde(rename = "transferTypesInfo")]
    pub transfer_types_info: std::collections::HashMap<String, models::TransferTypeInfo>,
    /// A UUID that uniquely identifies the account number. If the same account is used more than once, each card object will have a different id, but the fingerprint will stay the same.
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
    #[serde(rename = "billingDetails")]
    pub billing_details: models::BillingDetails,
    #[serde(rename = "bankAddress", skip_serializing_if = "Option::is_none")]
    pub bank_address: Option<models::BankAddress>,
    /// ISO-8601 UTC date/time format.
    #[serde(rename = "createDate")]
    pub create_date: String,
    /// ISO-8601 UTC date/time format.
    #[serde(rename = "updateDate")]
    pub update_date: String,
}

impl Wire {
    pub fn new(id: uuid::Uuid, status: models::ExternalFiatAccountStatus, description: String, tracking_ref: String, transfer_types_info: std::collections::HashMap<String, models::TransferTypeInfo>, fingerprint: String, billing_details: models::BillingDetails, create_date: String, update_date: String) -> Wire {
        Wire {
            id,
            status,
            description,
            tracking_ref,
            transfer_types_info,
            fingerprint,
            billing_details,
            bank_address: None,
            create_date,
            update_date,
        }
    }
}

