/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WireCreationRequest : Request object used to create a bank account (wires). Different fields are required depending on the bank country, see the guide documentation for the list of supported bank countries along with which ones support IBAN.
/// Request object used to create a bank account (wires). Different fields are required depending on the bank country, see the guide documentation for the list of supported bank countries along with which ones support IBAN.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WireCreationRequest {
    WireCreationRequestUs(Box<models::WireCreationRequestUs>),
    WireCreationRequestIban(Box<models::WireCreationRequestIban>),
    WireCreationRequestAccountNumber(Box<models::WireCreationRequestAccountNumber>),
}

impl Default for WireCreationRequest {
    fn default() -> Self {
        Self::WireCreationRequestUs(Default::default())
    }
}

