/*
 * All Circle APIs
 *
 * Circle's General, Core Functionality, Payments, Payouts, Accounts, and Crypto Payments APIs bundled into one OpenAPI Specification.
 *
 * The version of the OpenAPI document: 2.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WireInstruction {
    /// Circle tracking reference that needs to be set in the wire reference field.
    #[serde(rename = "trackingRef", skip_serializing_if = "Option::is_none")]
    pub tracking_ref: Option<String>,
    #[serde(rename = "beneficiary", skip_serializing_if = "Option::is_none")]
    pub beneficiary: Option<models::WireInstructionBeneficiary>,
    #[serde(rename = "beneficiaryBank", skip_serializing_if = "Option::is_none")]
    pub beneficiary_bank: Option<models::WireInstructionBeneficiaryBank>,
}

impl WireInstruction {
    pub fn new() -> WireInstruction {
        WireInstruction {
            tracking_ref: None,
            beneficiary: None,
            beneficiary_bank: None,
        }
    }
}

